### ISSUE TITLE
Request for `DefaultVpcDeletion` resource

### ISSUE THREAD

**Issue by lewyg** [crossplane-contrib/provider-upjet-aws#1052]
### What resource do you need?

Terraform Resource Name: resource does not exist in Terraform provider-aws

### What is your use case?

AWS accounts come with default Vpcs. In our case we don't want them, deletion of defaultVpc may help us with some cases, e.g.:
- without default Vpc it is harder to make deployment in the wrong location (you must specify one)
- there is a limit of Vpcs per region, if we don't use the default one, then it should be removed to free the space for another one

For each account, we need to delete default VPC and its dependencies after account creation. This needs to be done for all regions.

Currently, we use a workaround with provider-terraform and [awsutils](https://registry.terraform.io/providers/cloudposse/awsutils/latest/docs/resources/default_vpc_deletion). From the description:

> Best-practices call for not using the default VPC, but rather, creating a new set of VPCs as necessary. AWS Security Hub will flag the default VPCs as non-compliant if they aren't configured with best-practices. Rather than jumping through hoops, it's easier to delete to default VPCs. This task cannot be accomplished with the official AWS Terraform Provider, so this resource is necessary.

Is it possible to add DefaultVpcDeletion from awsutils to provider-aws? This would help us a lot. Thanks!

**Comment by mbbush** [comment]
Couldn't you also accomplish this by creating a https://marketplace.upbound.io/providers/upbound/provider-aws-ec2/v0.47.0/resources/ec2.aws.upbound.io/DefaultVPC/v1beta1 resource with `forceDelete: true` and then deleting it?

**Comment by lewyg** [comment]
@mbbush it cannot be destroyed with this method, because of IGW dependencies, found an issue that describes it: https://github.com/hashicorp/terraform-provider-aws/issues/23488

Apart from that, I'd like to have a single-step operation to delete default Vpcs, in the above approach I'd need to create a resource first, wait for it and then remove.

**Comment by erhancagirici** [comment]
Hi @lewyg  

The nature of this resource and implementation phase caused concerns. After thorough discussion and consideration, we believe that this resource is not Crossplane Resource Model (XRM) compliant in several ways.

- It is an unconventional destructive resource that creation of this resource deletes a cloud resource, and deleting this resource is a no-op and does not restore the old state.
  - This is also mentioned in the [cloudposse/awsutils](https://registry.terraform.io/providers/cloudposse/awsutils/latest/docs/resources/default_vpc_deletion)
  - it deletes a resource which in theory did not receive an explicit delete command
- It is an high-level pseudo-resource, that acts in an imperative fashion, and operates on the resources crossplane does not manage explicitly.
  - this is a violation of high fidelity
  - It "queries" for an unspecific resource without explicit import
  - such imperative approach and operating on other resources potentially can cause races with other, as those cloud resources can be managed by other "real" MRs.
  - An example is: there is a DefaultSubnet MR which manages the subnets of the default VPC. Those two will race.
This is in general applies for these kind of resources in such nature.

Research showed that these ideas were also captured at a [hashicorp forum discussion](https://discuss.hashicorp.com/t/destroy-default-vpc/2474/4) ([answer1](https://discuss.hashicorp.com/t/destroy-default-vpc/2474/3) and [answer2](https://discuss.hashicorp.com/t/destroy-default-vpc/2474/6) by maintainers) also mentioning the `cloudposse/awsutils` , explaining why VPCDeletion resource should not make it to the provider and it managing cloud resources that are not explicitly imported. `cloudposse/awsutils` repo readme also mentions that these are not accepted by terraform https://github.com/cloudposse/terraform-provider-awsutils?tab=readme-ov-file#terraform-provider-awsutils---

> This module is intended to be used as an escape hatch to accomplish all the hard things that will never be supported by the official provider due to strong (and valid) opinions of how providers should manage the lifecycle of a resource.

Because of the above similar reasons, we believe this resource should not be implemented due to XRM violations.
