### ISSUE TITLE
Sagemaker User Profile - Add Execution Role Selector

### ISSUE THREAD

**Issue by jasondroz** [crossplane-contrib/provider-upjet-aws#1193]
### What problem are you facing?

For `provider-aws-sagemaker` the `UserProfile` only allows a statically set IAM execution role under `spec.forProvider.userSettings`

### How could Official AWS Provider help solve your problem?

Add the selector feature like `spec.forProvider.userSettings.executionRoleSelector` to allow `matchControllerRef` and `matchLabels` to be used.

**Comment by turkenf** [comment]
Hi @jasondroz, thank you for bringing up this.

If you want to contribute we would appreciate it. [Here](https://github.com/crossplane/upjet/blob/v0.10.0/docs/add-new-resource-long.md#cross-resource-referencing) is a guide about adding new ref and selector, if you have any questions feel free to ask.

And [here](https://github.com/crossplane-contrib/provider-upjet-aws/blob/632aa6df85468904b694880811ffa0c88592801b/config/cloudfront/config.go#L39) is a current example, it is safer to use `TerraformName` instead of `Type`.
