### ISSUE TITLE
[Bug]: VPCEndpoint - SubnetIds array is not available 

### ISSUE THREAD

**Issue by aarontorg** [crossplane-contrib/provider-upjet-aws#1455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

ec2.aws.upbound.io/v1beta1 - VPCEndpoint

### Resource MRs required to reproduce the bug

        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: VPCEndpoint
        spec:
          forProvider:
            privateDnsEnabled: true
            serviceName: com.amazonaws.us-gov-west-1.ec2
            vpcEndpointType: Interface
            subnetIds:
              - subnet-xxx
            subnetConfiguration:
              - subnetIdSelector:
                  matchControllerRef: true
                  matchLabels:
                    access: private

### Steps to Reproduce

Try to create VPCEndpoint and assign subnetIds

### What happened?

Cannot assign subnetIds directly to the endpoint, must individually assign them which adds 100's of lines to the yaml.

### Relevant Error Output Snippet

```shell
Error when applying the composition: Warning: Composition "xnetworks.xp.sapns2.io" invalid for schema-aware validation: spec.resources[24].patches[0].toFieldPath: Invalid value: "spec.forProvider.subnetIds": field 'subnetIds' is not valid according to the schema
```

### Crossplane Version

1.16

### Provider Version

1.10.0

### Additional Info

[Terraform shows](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_endpoint) the subnetIds field and also states it is required to use subnetConfiguration. Any attempt to use subnetConfiguration will fail unless there are subnetIds.

**Comment by mergenci** [comment]
Thanks for your report @aarontorg. As far as I understand, lack of `subnetIds` is intentional. In VPCEndpoint configuration, [some fields are “moved to status”](https://github.com/crossplane-contrib/provider-upjet-aws/blob/v1.11.0/config/ec2/config.go#L152-L156), meaning that they are removed from `forProvider` and `initProvider`. As explained in the configuration comments, these fields are removed in favor of corresponding standalone resources, e.g., [VPCEndpointSubnetAssociation](https://marketplace.upbound.io/providers/upbound/provider-aws-ec2/v1.11.0/resources/ec2.aws.upbound.io/VPCEndpointSubnetAssociation/v1beta1) in `subnetIds`'s case.

The reason for doing so lies in [Crossplane Resource Model](https://github.com/crossplane/crossplane/blob/master/design/one-pager-managed-resource-api-design.md) (XRM). XRM prioritizes using standalone resources over managing resources embedded within other resources. Offering an option to do both is discouraged, because it may cause races between controllers.

**Comment by aarontorg** [comment]
Ok, kind of a bummer as that means will have to manage quite a bit more resources if we need to associate multiple subnets to this endpoint. 

Also, if I attempt to use "subnetConfiguration" and use a selectorId it complains that the subnet that it found is not in the subnetids list. In the terraform documentation it states that if a subnet is specified in the subnetConfiguration it must be in the subnetids ... so it seems there is a disconnect here.

**Comment by tsolodov** [comment]
Hi team, are you planning to fix it? Maybe remove fields that can't be used from VPCEndpoint to avoid confusion ?
